### ISSUE TITLE
address already in use

### ISSUE THREAD

**Issue by Logikoz** [pelican-dev/wings#39]
i created wing, but doesnt start correctly

OBS: VPS is empty, only wing is running, dont have any service running on 8080...
Even changing the port to any other, the error persists...

 ```
INFO: [Aug 26 01:42:35.797] configuring internal webserver host_address=0.0.0.0 host_port=8080 use_auto_tls=false use_ssl=false
FATAL: [Aug 26 01:42:35.797] failed to configure HTTP server error=listen tcp 0.0.0.0:8080: bind: address already in use

Stacktrace:
listen tcp 0.0.0.0:8080: bind: address already in use
github.com/pelican-dev/wings/cmd.rootCmdRun
	github.com/pelican-dev/wings/cmd/root.go:397
github.com/spf13/cobra.(*Command).execute
	github.com/spf13/cobra@v1.8.0/command.go:987
github.com/spf13/cobra.(*Command).ExecuteC
	github.com/spf13/cobra@v1.8.0/command.go:1115
github.com/spf13/cobra.(*Command).Execute
	github.com/spf13/cobra@v1.8.0/command.go:1039
github.com/pelican-dev/wings/cmd.Execute
	github.com/pelican-dev/wings/cmd/root.go:71
main.main
	github.com/pelican-dev/wings/wings.go:17
runtime.main
	runtime/proc.go:267
runtime.goexit
	runtime/asm_amd64.s:1650
```
	
Here my config:
```
debug: false
uuid: b5137727-90a9-481a-bd62-a232248babf4
token_id: EnDNSYrAXcgMbcOq
token: MY_TOKEN
api:
  host: 0.0.0.0
  port: 8080
  ssl:
    enabled: false
    cert: /etc/letsencrypt/live/192.168.1.116/fullchain.pem
    key: /etc/letsencrypt/live/192.168.1.116/privkey.pem
  upload_limit: 256
system:
  data: /var/lib/pelican/volumes
  sftp:
    bind_port: 2022
allowed_mounts: []
remote: 'http://MY_URL'

```

On panel:
![image](https://github.com/user-attachments/assets/e0cd0cfb-b73c-461e-b93d-5ef94692d8cc)

**Comment by RMartinOscar** [comment]
Hey something is already using the 8080 port, if the service is running you can't manually run wings,
For those issues please prefer using the [Discord](https://discord.gg/pelican-panel)

**Comment by Logikoz** [comment]
> Hey something is already using the 8080 port, if the service is running you can't manually run wings, You can check what's using it with `ss -tulnp | grep 8080` For those issues please prefer using the [Discord](https://discord.gg/pelican-panel) rather then github

tcp   LISTEN 0      4096                     *:8080             *:*
