### ISSUE TITLE
Allow mounts inside /home/container

### ISSUE THREAD

**Issue by zabszk** [pelican-dev/wings#41]
Hi,

I would like to suggest removal of a constraint preventing mounts inside of `/home/container` (added in https://github.com/pelican-dev/wings/commit/7c9ca5266f94fa171a404a3b0b215e926cd9f80c). We have been using such mounts in Pterodactyl (before we migrated to Pelican - we know it's not officially supported in Pterodactyl, but there is no check) and it worked fine. Currently we manually mount it using bash and it works as well.

I don't see a reason why such mounts are not supported if they work fine. I suggest removal of that check. If there are some edge cases where such mounts don't work, it's better to add a warning, because in many cases they work fine.

**Comment by QuintenQVD0** [comment]
Mounting 2 times the same path can cause issues for aplication as a path exsist 2 times on disk.

**Comment by zabszk** [comment]
> Mounting 2 times the same path can cause issues for aplication as a path exsist 2 times on disk.

That's an application issue in that case. Pelican shouldn't create restrictions for all apps just in case some app doesn't support it. It should be a warning in that case, not a restriction.

There can be many more cases (not related to mounts) that app doesn't support and pelican doesn't check for it.

**Comment by Boy132** [comment]
> I don't see a reason why such mounts are not supported if they work fine.

AFAIK this restriction has historical reasons. Docker itself used to not support it but added support at some point. It just hasn't adjusted/ updated in Pterodactyl at the time.

**Comment by zabszk** [comment]
> > I don't see a reason why such mounts are not supported if they work fine.
> 
> AFAIK this restriction has historical reasons. Docker itself used to not support it but added support at some point. It just hasn't adjusted/ updated in Pterodactyl at the time.

That could be the reason. Pterodactyl doesn't have any check to prevent such mounts (maybe it had such check in the past), it only says in the documentation that such mounts are not supported. The check to prevent such mounts has been added to Pelican in 7c9ca5266f94fa171a404a3b0b215e926cd9f80c (at that time there was no such check in Pterodactyl).

**Comment by zabszk** [comment]
I checked Pterodactyl repository. There was never a check to prevent such mounts and old version of documentation clearly says that it was due to Docker limitation (https://github.com/pterodactyl/documentation/commit/e08c8f4cd0eb003ad5139d253a93e1547e06bfef#diff-381d4a108eb9141de271bb8caebfde8b61b25cc4122aab21eed43e7a2471d04d). In that case the check can be safely removed, because docker supports it.

**Comment by QuintenQVD0** [comment]
Maybe i will add a config toggle for it. but the default will block it and for good reasons.

**Comment by zabszk** [comment]
> Maybe i will add a config toggle for it. but the default will block it and for good reasons.

The original reason was that docker doesn't support it and that's no longer the case - docker supports it. I don't see any reason of not allowing such mounts, especially if only Pelican has such restriction.

I can make a quick PR removing that check if you wish. We already have a fork with that check removed.

**Comment by QuintenQVD0** [comment]
> > Maybe i will add a config toggle for it. but the default will block it and for good reasons.
> 
> The original reason was that docker doesn't support it and that's no longer the case - docker supports it. I don't see any reason of not allowing such mounts, especially if only Pelican has such restriction.
> 
> I can make a quick PR removing that check if you wish. We already have a fork with that check removed.

removing that will not happen as in linux it should not be possible to mount the same dir or sub dir twice.

We are internaly discusing this but removing this is not a real option

**Comment by QuintenQVD0** [comment]
see: <https://github.com/pterodactyl/panel/issues/4387>

**Comment by zabszk** [comment]
> see: [pterodactyl/panel#4387](https://github.com/pterodactyl/panel/issues/4387)

Take a look at the issue "The docs tell you that you can not mount [...] if you mount to that dir is still works". The issue is that the docs says you can't, but it works fine. That's the reported issue.

> removing that will not happen as in linux it should not be possible to mount the same dir or sub dir twice.

Works fine in linux (see screenshots below) and man page of command "mount" doesn't mention such restriction https://linux.die.net/man/8/mount. Can you provide some source that it should not be possible in linux?

![2024-09-14_16-49-33](https://github.com/user-attachments/assets/f552d88f-8884-4c6c-9227-a279711faba7)
![2024-09-14_16-49-47](https://github.com/user-attachments/assets/54131b1e-2544-4865-9d1d-4b1dc44380c3)

**Comment by QuintenQVD0** [comment]
there were some issues in the past when I tried that, that may have changed.

It is up to Kubi or parker if they want to keep it or not

**Comment by zabszk** [comment]
> there were some issues in the past when I tried that, that may have changed.
> 
> It is up to Kubi or parker if they want to keep it or not

If there were some issues (other than docker not supporting it - that's no longer the case) then of course adding a config or a warning in admin panel is perfectly reasonable (which I suggested in the issue body itself).

**Comment by zabszk** [comment]
> It was like if you try to mount a MC plugin dir the config would come in the home mount and the plugins would try to load out of the extra mount and just then refuse to load. I will add a config toggle for this that allows you disable this check

I don't really understand the issue then, because the `pl` command shows it as loaded and just Essentials couldn't create a config, which can be an application issue... anyway, it's not really important here.

Adding a config toggle works for us. Thanks a lot. This is not urgent, because for now we just use our fork (with the check removed), but it will make our lives much easier to just use the official Pelican builds.

**Comment by QuintenQVD0** [comment]
> > It was like if you try to mount a MC plugin dir the config would come in the home mount and the plugins would try to load out of the extra mount and just then refuse to load. I will add a config toggle for this that allows you disable this check
> 
> I don't really understand the issue then, because the `pl` command shows it as loaded and just Essentials couldn't create a config, which can be an application issue... anyway, it's not really important here.
> 
> Adding a config toggle works for us. Thanks a lot. This is not urgent, because for now we just use our fork (with the check removed), but it will make our lives much easier to just use the official Pelican builds.

I do understand the need so I am working on it ;)

**Comment by QuintenQVD0** [comment]
@zabszk I wrote some code, could you please try it

**Comment by zabszk** [comment]
> > > It was like if you try to mount a MC plugin dir the config would come in the home mount and the plugins would try to load out of the extra mount and just then refuse to load. I will add a config toggle for this that allows you disable this check
> > 
> > 
> > I don't really understand the issue then, because the `pl` command shows it as loaded and just Essentials couldn't create a config, which can be an application issue... anyway, it's not really important here.
> > Adding a config toggle works for us. Thanks a lot. This is not urgent, because for now we just use our fork (with the check removed), but it will make our lives much easier to just use the official Pelican builds.
> 
> I do understand the need so I am working on it ;)

Thank you. I'm not really familiar with go language, so I can't help you with that. Removing the check was the best what I could do :).

Btw. so far it's the only issue we encountered after migrating from Pterodactyl to Pelican. Overall the experience is better. (We are silently waiting for some features you guys are already working on)

> @zabszk I wrote some code, could you please try it
Sure. We will test it today and let you know.

**Comment by zabszk** [comment]
> @zabszk I wrote some code, could you please try it

My colleague tested the PR (both config options - true and false) and it works as expected.
@QuintenQVD0
